/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itenas.projectuas.view;

import com.itenas.projectuas.entity.Hewan;
import com.itenas.projectuas.entity.User;
import com.itenas.projectuas.utilites.AccountLoggedIn;
import com.itenas.projectuas.utilites.ProductSelected;
import com.itenas.projectuas.utilites.Transaction;

/**
 *
 * @author M Alif Mi'raj Jabbar
 */
public class viewKonfirmasiPembayaran extends javax.swing.JFrame {

    /**
     * Creates new form viewKonfirmasiPembayaran
     */
    Hewan hewan = ProductSelected.getHewan();
    User user = AccountLoggedIn.getCurrentUser();
    public viewKonfirmasiPembayaran() {
        initComponents();
        setLocationRelativeTo(null);
        hewan = ProductSelected.getHewan();
        user = AccountLoggedIn.getCurrentUser();
        showInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_hewan = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtHewan = new javax.swing.JLabel();
        txtBerat = new javax.swing.JLabel();
        txtHarga = new javax.swing.JLabel();
        lbl_harga = new javax.swing.JLabel();
        lbl_berat = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_transfer = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_kembalian = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Transaksi Berhasil");

        lbl_hewan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_hewan.setForeground(new java.awt.Color(0, 0, 0));
        lbl_hewan.setText("Hewan");

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Kembali ke Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtHewan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtHewan.setForeground(new java.awt.Color(0, 0, 0));
        txtHewan.setText("Hewan dibeli: ");

        txtBerat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtBerat.setForeground(new java.awt.Color(0, 0, 0));
        txtBerat.setText("Berat:");

        txtHarga.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtHarga.setForeground(new java.awt.Color(0, 0, 0));
        txtHarga.setText("Harga: ");

        lbl_harga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_harga.setForeground(new java.awt.Color(0, 0, 0));
        lbl_harga.setText("Hewan");

        lbl_berat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_berat.setForeground(new java.awt.Color(0, 0, 0));
        lbl_berat.setText("Hewan");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Transfer: ");

        lbl_transfer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_transfer.setForeground(new java.awt.Color(0, 0, 0));
        lbl_transfer.setText("Hewan");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Kembalian: ");

        lbl_kembalian.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_kembalian.setForeground(new java.awt.Color(0, 0, 0));
        lbl_kembalian.setText("Hewan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(104, 104, 104))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHewan)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtBerat)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_berat)))
                                .addGap(18, 18, 18)
                                .addComponent(lbl_hewan))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtHarga)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_harga))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_transfer))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_kembalian)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_hewan)
                    .addComponent(txtHewan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHarga)
                    .addComponent(lbl_harga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBerat)
                    .addComponent(lbl_berat))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lbl_transfer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lbl_kembalian))
                .addGap(66, 66, 66)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new viewDashboardUser().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    private void showInfo() {
        lbl_hewan.setText(hewan.getNamaHewan());
        lbl_harga.setText(Double.toString(hewan.getHarga()));
        lbl_berat.setText(Double.toString(hewan.getBerat()));
        lbl_transfer.setText(Double.toString(Transaction.getTransfer()));
        lbl_kembalian.setText(Double.toString(Transaction.getSelisih()));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewKonfirmasiPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewKonfirmasiPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewKonfirmasiPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewKonfirmasiPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewKonfirmasiPembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_berat;
    private javax.swing.JLabel lbl_harga;
    private javax.swing.JLabel lbl_hewan;
    private javax.swing.JLabel lbl_kembalian;
    private javax.swing.JLabel lbl_transfer;
    private javax.swing.JLabel txtBerat;
    private javax.swing.JLabel txtHarga;
    private javax.swing.JLabel txtHewan;
    // End of variables declaration//GEN-END:variables

    
}
