/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itenas.projectuas.view;

import com.itenas.projectuas.controller.ControllerTransaksi;
import com.itenas.projectuas.entity.Transaksi;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author M Alif Mi'raj Jabbar
 */
public class viewDashboardAdmin extends javax.swing.JFrame {

    ControllerTransaksi conTrans = new ControllerTransaksi();
    private DefaultTableModel model;

    /**
     * Creates new form viewDashboardAdmin
     */
    public viewDashboardAdmin() {
        initComponents();
        setLocationRelativeTo(null);

        model = new DefaultTableModel();

        tbl_dataTransaksi.setModel(model);

        model.addColumn("Invoice");
        model.addColumn("Nama Hewan");
        model.addColumn("Berat");
        model.addColumn("Username");
        model.addColumn("Tanggal Beli");
        model.addColumn("Harga");
        model.addColumn("Nama Tujuan");
        model.addColumn("Rekening");
        model.addColumn("Jenis Bank");
        model.addColumn("Saldo");
        model.addColumn("Tagihan");
        model.addColumn("Selisih");
        getData();
    }

    public final void getData() {
         DefaultTableModel dtm = (DefaultTableModel) tbl_dataTransaksi.getModel();
        dtm.setRowCount(0);

        List<Transaksi> listTransksi = conTrans.showTransaksiAdmin();
        String[] data = new String[12]; // Adjust the size according to the number of columns
        for (Transaksi newTransaksi : listTransksi) {
            data[0] = newTransaksi.getInvoice();
            data[1] = newTransaksi.getNamaHewan();
            data[2] = Double.toString(newTransaksi.getBerat());
            data[3] = newTransaksi.getUsername();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            String stringTanggalBeli = newTransaksi.getTanggalBeli().format(formatter);
            data[4] = stringTanggalBeli;
            data[5] = Double.toString(newTransaksi.getHarga());
            data[6] = newTransaksi.getNamaTujuan();
            data[7] = newTransaksi.getRekening();
            data[8] = newTransaksi.getJenisBank();
            data[9] = Double.toString(newTransaksi.getSaldo());
            data[10] = Double.toString(newTransaksi.getTagihan());
            data[11] = Double.toString(newTransaksi.getSelisih());
            dtm.addRow(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_dataTransaksi = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        Btn_manageuser = new javax.swing.JButton();
        Btn_manageHewan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        tbl_dataTransaksi.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tbl_dataTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Invoice", "Nama Hewan", "Berat", "Username", "Tanggal Beli", "Harga", "Nama Tujuan", "Rekening", "Jenis Bank", "Saldo", "Tagihan", "Selisih"
            }
        ));
        jScrollPane1.setViewportView(tbl_dataTransaksi);

        jPanel2.setBackground(new java.awt.Color(0, 204, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hello Admin");

        btn_logout.setBackground(new java.awt.Color(255, 255, 255));
        btn_logout.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(51, 204, 0));
        btn_logout.setText("Log out");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        Btn_manageuser.setBackground(new java.awt.Color(255, 255, 255));
        Btn_manageuser.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Btn_manageuser.setForeground(new java.awt.Color(51, 204, 0));
        Btn_manageuser.setText("Inspect user");
        Btn_manageuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_manageuserActionPerformed(evt);
            }
        });

        Btn_manageHewan.setBackground(new java.awt.Color(255, 255, 255));
        Btn_manageHewan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Btn_manageHewan.setForeground(new java.awt.Color(51, 204, 0));
        Btn_manageHewan.setText("Manage Hewan");
        Btn_manageHewan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_manageHewanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(Btn_manageHewan)
                .addGap(37, 37, 37)
                .addComponent(Btn_manageuser)
                .addGap(26, 26, 26)
                .addComponent(btn_logout)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_logout)
                        .addComponent(Btn_manageuser)
                        .addComponent(Btn_manageHewan))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        int logout = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin logout ? ", "Warning", JOptionPane.YES_NO_OPTION);
        if (logout == JOptionPane.YES_OPTION) {
            new viewLogin().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void Btn_manageuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_manageuserActionPerformed
        new viewShowUsers().setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_manageuserActionPerformed

    private void Btn_manageHewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_manageHewanActionPerformed
        new ViewManageHewan().setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_manageHewanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewDashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewDashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewDashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewDashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewDashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_manageHewan;
    private javax.swing.JButton Btn_manageuser;
    private javax.swing.JButton btn_logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_dataTransaksi;
    // End of variables declaration//GEN-END:variables
}
